version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: restify-db
    environment:
      POSTGRES_DB: restify_db
      POSTGRES_USER: restify_user
      POSTGRES_PASSWORD: restify_pwd
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: restify-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restify_db
      SPRING_DATASOURCE_USERNAME: restify_user
      SPRING_DATASOURCE_PASSWORD: restify_pwd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: UmaChaveUltraSecreta12345
      APP_JWT_EXPIRATION_MS: 3600000
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: